# -*- coding: utf-8 -*-
"""pydp-27_PETROV_I_A_dz05.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vLWO5VfurdySkXEGUJDCVr8a-T8m1ob8

#Петров Игорь (pydp-27)

##ДЗ 05 "Работа с ФС и модули"

### Задание 1
"""

#Задание 1
import json

f = open('sample_data/purchase_log.txt', 'r', encoding='utf-8')

size = int(input('Сколько загрузить строк:'))
purchases = {}

for i, line in enumerate(f):
  if i > 0: 
    line = json.loads(line)
    purchases[i] = {line.get('user_id'): line.get('category')}
    print(purchases.get(i))
  if i == size: break

f.close()

"""###Задание 2"""

#Задание 2
import json

f_purs = open('sample_data/purchase_log.txt', 'r', encoding='utf-8')
f_vis = open('sample_data/visit_log.csv', 'r', encoding='utf-8')
f_funnel = open('sample_data/funnel.csv', 'w', encoding='utf-8')

vis_line = []
purchases = {}

for i, line in enumerate(f_purs):
  if i > 0: 
    line = json.loads(line)
    purchases[i] = {line.get('user_id'): line.get('category')}
   
for i, line in enumerate(f_vis):
  if i > 0: 
    vis_line = line.strip().split(',')
    [f_funnel.write(f'{str(value)}\n') for key, value in purchases.items() if vis_line[0] in value] 
  if i == 1000: break  #для примера

f_purs.close()
f_vis.close()
f_funnel.close()